# Generated by Django 3.0.5 on 2020-04-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
